---
- name: create temp directory
  action: mktemp_dir
  register: _tmp

- name: fetch package
  get_url: >
    url={{ solr_pkg_url }}
    dest={{ _tmp.path }}/{{ solr_pkg_url | basename }}

- name: unpack package to the temp directory
  command: >
    tar -xzf '{{ solr_pkg_url | basename }}'
    chdir={{ _tmp.path }}

- name: copy WAR file to destination
  shell: >
    cp -R {{ _tmp.path }}/solr-*/dist/solr-*.war {{ solr_home_dir }}/solr.war

- name: delete the temp directory
  file: >
    path={{ _tmp.path }}
    state=absent
  tags: cleanup
